### PR TITLE
Added roo and dullard into benchmark

### PR DESCRIPTION
**Pull request by g3d**

### CODE REVIEW

**Comment by ebeigarts** [comment]
I just added oxcelix benchmarks. Can you rebase this?

**Comment by ebeigarts** [comment]
And also can you order the output alphabeticaly by gem names?

**Comment by g3d** [comment]
@ebeigarts rebased & ordered.

**Comment by ebeigarts** [comment]
Thanks, good to see that is still the fastest. :)

**Comment by g3d** [comment]
@ebeigarts I created that gist yesterday https://gist.github.com/g3d/6ce15fb55ec6db8a60c3. Good to see the results in README now ;)

**Comment by g3d** [comment]
BTW there is a duplication of 'Shared Strings' in README

**Comment by ebeigarts** [comment]
Thantks, removed the duplicate line
---
Edgars Beigarts
MAK IT

**Pull request merged**
